development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:2dcf130ac388d980cb441d83b87cbb05@albacore.redistogo.com:10178/
  channel_prefix: ocsc-web-tms
