default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: deploy
  password: 

development:
  <<: *default
  database: ocsc_web_tms_development
test:
  <<: *default
  database: ocsc_web_tms_test

production:
  <<: *default
  database: ocsc_web_tms_production
